
services:
  db:
    image: postgres
    container_name: my_postgres
    environment:
      POSTGRES_USER: cedric
      POSTGRES_PASSWORD: 2412
      POSTGRES_DB: invoices
    ports:
      - "5432:5432"
    volumes:
      - ./postgresData:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
